# Site settings {{ site.title }}
title: phil.sergi
description: "A mix of timeless Christian truth and transient technology posts."
url: "https://philsergi.com"
quote: >
  "There is a way which seemeth right unto a man, but the end thereof are the ways of death." –Proverbs 14:12
plugins:
  - jekyll-sitemap
jekyll_compose:
  auto_open: true
  draft_default_front_matter:
    source:
    author:
    categories: []

# Build settings
permalink: :title
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
