# Site settings {{ site.title }}
title: Phil Sergi
header: phil.sergi
description: "A mix of timeless Christian truth and transient technology posts."
url: "https://philsergi.com"
quote: >
  "There is a way which seemeth right unto a man, but the end thereof are the ways of death." –Proverbs 14:12
author:
  name: Phil Sergi
  url: https://philsergi.com
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
jekyll_compose:
  auto_open: true
  draft_default_front_matter:
    source:
    author:
    categories: []

# Build settings
permalink: :title
markdown: kramdown
kramdown:
  toc_levels: 2..2
exclude:
  - Gemfile
  - Gemfile.lock
