# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: phil.sergi
email: phil.sergi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A mix of timeless Christian truth and transient technology posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://philsergi.com" # the base hostname & protocol for your site, e.g. http://example.com
quote: >
  "There is a way which seemeth right unto a man, but the end thereof are the ways of death." –Proverbs 14:12

# Build settings
permalink: :title
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
